#Reference cs.boisestate.edu/~cs253/handouts/make-handout.pdf
#For more information regarding make
CC = gcc
CFLAGS = -Wall -g
all : main.o f1.o f2.o f3.o
	gcc -Wall -g -o hello main.o f1.o f2.o f3.o
run:
	./hello
clean:
	rm -f *.o hello
	
